steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --no-cache
      - -t
      - ${_IMAGE_REPOSITORY}/vpo-corp-platform:${COMMIT_SHA}
      - .
      - -f
      - Dockerfile

  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE_REPOSITORY}/vpo-corp-platform:${COMMIT_SHA}

  - id: Deploy API
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - ${_API_SERVICE}
      - --platform=managed
      - --image=${_IMAGE_REPOSITORY}/vpo-corp-platform:${COMMIT_SHA}
      - --labels=managed-by=cloud-build,commit-sha=${COMMIT_SHA}
      - --set-cloudsql-instances=${_CLOUDSQL_CONNECTION_NAME}
      - --update-env-vars=VPO_CLOUDSQL_CONNECTION_NAME=${_CLOUDSQL_CONNECTION_NAME},VPO_POSTGRES_APPLICATION_NAME=vpo-corp-api,VPO_POSTGRES_POOL_MIN_SIZE=1,VPO_POSTGRES_POOL_MAX_SIZE=4,VPO_POSTGRES_POOL_TIMEOUT_SECONDS=10,VPO_POSTGRES_POOL_MAX_WAITING=16,VPO_POSTGRES_POOL_MAX_LIFETIME_SECONDS=1800,VPO_POSTGRES_POOL_MAX_IDLE_SECONDS=300
      - --region=${_REGION}
      - --quiet

  - id: Deploy report Job
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update
      - ${_REPORT_JOB}
      - --image=${_IMAGE_REPOSITORY}/vpo-corp-platform:${COMMIT_SHA}
      - --set-cloudsql-instances=${_CLOUDSQL_CONNECTION_NAME}
      - --update-env-vars=VPO_CLOUDSQL_CONNECTION_NAME=${_CLOUDSQL_CONNECTION_NAME},VPO_POSTGRES_APPLICATION_NAME=vpo-report-job,VPO_POSTGRES_POOL_MIN_SIZE=0,VPO_POSTGRES_POOL_MAX_SIZE=2,VPO_POSTGRES_POOL_TIMEOUT_SECONDS=10,VPO_POSTGRES_POOL_MAX_WAITING=4,VPO_POSTGRES_POOL_MAX_LIFETIME_SECONDS=1800,VPO_POSTGRES_POOL_MAX_IDLE_SECONDS=300
      - --region=${_REGION}
      - --quiet

images:
  - ${_IMAGE_REPOSITORY}/vpo-corp-platform:${COMMIT_SHA}

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: MUST_MATCH

substitutions:
  _API_SERVICE: vpo-corp-api
  _CLOUDSQL_CONNECTION_NAME: vpo-corp-royalties:us-central1:vpo-corp-postgres-ssd
  _IMAGE_REPOSITORY: us-central1-docker.pkg.dev/vpo-corp-royalties/cloud-run-source-deploy/royalties_pipeline
  _REGION: us-central1
  _REPORT_JOB: vpo-royalty-report-job

tags:
  - vpo-corp-platform
  - production
